name: CodeNotary
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@master
     
     - name: Verify
       uses: vchain-us/verify-action@master
       with:
         signerID: 0x163ce77e59c67f1acfab0ffda57db7c4a9b3eee5
